### ISSUE TITLE
nil handling does not work as described

### ISSUE THREAD

**Issue by archSeer** [schrockwell/bodyguard#12]
"nil data will not defer to any policy module, and will fail authorization by default. _If the :policy option is explicitly specified, then that policy module will be used, passing nil as the data._"

But the actual code will ignore the explicitly specified policy and fail: https://github.com/schrockwell/bodyguard/blob/936bdfc11477ce69e539122c7f28e6a1d33f6f71/lib/bodyguard/controller.ex#L31

**Comment by schrockwell** [comment]
Good catch, thanks. The desired functionality must have been lost in a refactor. Let me take a quick look at this – should be a simple fix.

**Comment by schrockwell** [comment]
Fixed and published v0.2.1. Thanks @archSeer.
