### ISSUE TITLE
How do you handle cases when role is defined in another model?

### ISSUE THREAD

**Issue by abitdodgy** [schrockwell/bodyguard#16]
For example, in scenarios where you have a many-to-many association between, say, `companies` and `users`, where the `role` column is defined in the `memberships` schema.

In this scenario, the current user is not enough. We also need the membership record.

**Comment by abitdodgy** [comment]
Easy enough, I suppose:

```elixir
  def can?(%User{id: user_id}, action, %Organisation{id: org_id})
  when action in [:edit, :update] do
    case Repo.get_by(Membership, user_id: user_id, organisation_id: org_id, role: :admin) do
      nil -> false
      _ -> true
    end
  end
```

**Comment by schrockwell** [comment]
Can you preload the `user.memberships` association prior to authorization? If so, then in your policy you can do everything in-memory without another query: 

```elixir
def can?(%User{id: user_id, memberships: memberships}, action, %Organisation{id: org_id})
when action in [:edit, :update] do
  Enum.any?(memberships, &match?(&1, %Membership{organisation_id: org_id, role: :admin}))
end
```

**Comment by abitdodgy** [comment]
@schrockwell great suggestion as well. Thanks.
