### ISSUE TITLE
protocol Ecto.Queryable not implemented for []

### ISSUE THREAD

**Issue by zimt28** [schrockwell/bodyguard#20]
Hi!

I've been using policies so far and just tried to add scopes, however I get the following error:
```
protocol Ecto.Queryable not implemented for []
```

```elixir
defmodule App.Case.Policy do
  import Ecto.Query

  def can?(_user, _action, _case), do: true

  def scope(_user, _action, scope), do: scope
end
```

All I've added is the following line (policies work fine for the same controller):

```elixir
def index(conn, _params) do
  IO.inspect scope(conn, Case)
  # ...
```
I've looked at the documentation but couldn't find a difference, what's wrong with my code?

Thanks!

**Comment by zimt28** [comment]
Looks like I'm getting empty lists for `_action` and `scope`

**Comment by zimt28** [comment]
Simple solution: I used the `master` Readme, but should have used https://github.com/schrockwell/bodyguard/tree/v0.5.0.

**Comment by schrockwell** [comment]
Yeah, sorry about that, I'm in the process of making some breaking API changes. Glad you figured it out.
