### ISSUE TITLE
Implementation of permitted attributes

### ISSUE THREAD

**Issue by cc3c** [schrockwell/bodyguard#37]
I have migrated my app from phoenix 1.2 to 1.3. But in order to upgrade Bodyguard 1 to 2, my app uses the api of permitted attributes that was available in 1.0.0
I asume this enhancement is in your roadmap, this is only a reminder.
Thnx in advance.

**Comment by schrockwell** [comment]
Thanks, this was not something I was considering but I will definitely take another look. Should be simple enough to add.
