### ISSUE TITLE
How to render changeset errors when using with?

### ISSUE THREAD

**Issue by abitdodgy** [schrockwell/bodyguard#39]
Is it possible to render changeset errors when using `with` syntax? For example:

```
    with :ok <- Bodyguard.permit(Media, :manage_links, current_user, post),
      {:ok, _link} <- Media.create_post_link(post, link_params)
    do
      conn
      |> redirect(to: get_location(conn))
    else
      {:error, %Ecto.Changeset{} = changeset} ->
        render conn, "new.html", user: current_user, changeset: changeset
    end
```

This will fail with a `WithClause` error because there's no clause that matches `{:error, :unauthorized}`.

However, dropping down to `action_fallback`:

```
    with :ok <- Bodyguard.permit(Media, :manage_links, current_user, post),
      {:ok, _link} <- Media.create_post_link(post, link_params)
    do
      conn
      |> redirect(to: get_location(conn))
    end
```

Doesn't render the template along with the changeset to display the errors.

Is it possible to use a `with` syntax and still show validation errors?

**Comment by schrockwell** [comment]
Define a catch-all clause in the `else` block to ensure that any other error result is matched.

```elixir
    with :ok <- Bodyguard.permit(Media, :manage_links, current_user, post),
      {:ok, _link} <- Media.create_post_link(post, link_params)
    do
      conn
      |> redirect(to: get_location(conn))
    else
      {:error, %Ecto.Changeset{} = changeset} ->
        render conn, "new.html", user: current_user, changeset: changeset
      error -> error # <-- fall through to fallback controller
    end
```

**Comment by schrockwell** [comment]
Side note: it's cases like this that make me think recommending the bang methods might actually be a better pattern. This is so much easier to read, IMO:

```elixir
    Bodyguard.permit!(Media, :manage_links, current_user, post)

    case Media.create_post_link(post, link_params) do
      {:ok, _link} ->
        redirect conn, to: get_location(conn)
      {:error, changeset} ->
        render conn, "new.html", user: current_user, changeset: changeset
    end
```

If you believe authorization failure is truly an _exceptional_ case (i.e. is shouldn't happen under normal circumstances), then it makes sense to throw an exception.

**Comment by abitdodgy** [comment]
> Side note: it's cases like this that make me think recommending the bang methods might actually be a better pattern, in general. This is so much easier to read, IMO:

I agree with you there. As for adding an additional clause, I tried to do that originally, but I didn't like adding another clause for authorization. Thanks!
