### ISSUE TITLE
Return type of Bodyguard.Authorize.init/1

### ISSUE THREAD

**Issue by NobbZ** [schrockwell/bodyguard#52]
The function mentioned in the subject does return a map, this is not allowed in Plug 1.0 (according to the callbacks specs).

The specs do allow a map only since 1.3.0.

**Comment by NobbZ** [comment]
I took a quick look and phoenix 1.3.3 depends on `{:plug, "~> 1.3.3 or ~> 1.4"}`.

Since you target phoenix 1.3s contexts, you should probably do the same.

**Comment by schrockwell** [comment]
Fixed in 2.3. Good eye - thank you!
