### ISSUE TITLE
Rename authy

### ISSUE THREAD

**Issue by schrockwell** [schrockwell/bodyguard#6]
Twilio has [a trademark for Authy](https://trademarks.justia.com/864/89/authy-86489618.html), their iOS two-factor authentication app.

It could be a an issue in the future, and it's going to be infinitely easier to rename the package now before anybody is actually using it.

We can [rename the GitHub repo](https://help.github.com/articles/renaming-a-repository/) with no problem, since it will redirect everything. 

We should just remove the package from Hex and publish it under a new name. There is a mechanism in hex to point users to the new package, but I think it's young enough we can nip this in the bud without affecting anybody.

We'll also need a new name. Thoughts @bencates?

**Comment by ejreynolds** [comment]
👍

**Comment by bencates** [comment]
Maybe "eleven", as in "a11n". And also "this one goes to eleven".

**Comment by schrockwell** [comment]
I'm not sure we should go that clever... I really like sticking with the auth/policy naming scheme to keep it relatively explicit, but still unique. Maybe something with an `_ex` or `_phoenix` since this will probably be a true Phoenix-only package from here on out.

* authr - also looks like maybe a trademark issue?
* author - too confusing?
* policy_ex
* ex_policy
* phoenix_policy
* ex_pundit - kind of a play on "moving on" from Ruby and Pundit

**Comment by schrockwell** [comment]
expunge (v) - erase or remove completely

`ex_punge`?

**Comment by bencates** [comment]
I'd steer clear of phoenix_*; feels too official. We could go with
something anthropomorphic. Bouncer, hall monitor, border guard, etc.

I'm just getting to the park, so I'll be offline until this evening.

**Comment by schrockwell** [comment]
Bouncer - your app is throwing a party, and some users aren't invited

Two syllables, one word, easy to remember. I really dig it.

**Comment by schrockwell** [comment]
Doh, already taken. Twice.
https://hex.pm/packages?_utf8=✓&search=Bouncer&sort=downloads

I like the anthro idea though.

**Comment by schrockwell** [comment]
From Thesaurus.com:

Main Entry: bodyguard
Part of Speech: noun
Definition: protector
Synonyms: bouncer, escort, guardian, minder, muscle*, praetorian, security
guard

Also I'm throwing in: doorman

**Comment by schrockwell** [comment]
Some "bouncer" synonyms, available on Hex:
* bodyguard
* muscle
* protector
* garrison

**Comment by bencates** [comment]
We could do a lot worse than bodyguard.

**Comment by schrockwell** [comment]
Okay cool, we will go with `bodyguard`. I like it.

We can put in all the API changes into `bodyguard v0.2.0` and do the rename at the same time.

**Comment by schrockwell** [comment]
This is done on develop. Still need to bump version and rename GitHub project.

**Comment by schrockwell** [comment]
Done! I made a new branch called `authy-deprecated`, bumped to `v0.1.1`, added a deprecation warning in the Hex package description, and pushed it to Hex.

`bodyguard v0.2.0` is also published and merged to `master`.

\o/ Thanks for all your help @bencates. I really believe this package is better as a result of your contributions. I'm already dog-fooding it!

**Comment by bencates** [comment]
Great!  I'm going to be pulling it into my project later this week.
