### ISSUE TITLE
Allow to return `{:ok, data}` from authorize callbacks?

### ISSUE THREAD

**Issue by ssbb** [schrockwell/bodyguard#86]
Hi!

I am thinking about about possibility to provide some extra context for permissions. Like not the just fact that user can do something but also **why**. Something like this:

```elixir
def authorize(:edit_post, user, post) do
  cond do
    user.is_admin -> {:ok, :admin}
    post.user_id == user.id -> {:ok, :author}
    true -> {:error, "Only adminisrators and authors can edit posts."}
  end
end
```

I am thinking about preparing PR but does not make sense if you think it don't fit into lib scope etc.

**Comment by joshchernoff** [comment]
Not saying you should not do this, but honestly I would keep the "why" closer to the surface. Like the controller.  The reason is you may want to responds according to your interface later.

**Comment by schrockwell** [comment]
This would unfortunately break the core API specification and would require a major version bump per SemVer, which is just not in the cards right now. And also I agree with @joshchernoff that this is solving an issue _different_ from authorization. Thank you for the proposal.
