### ISSUE TITLE
Is this project still maintained and/or relevant?

### ISSUE THREAD

**Issue by goulvenclech** [schrockwell/bodyguard#88]
Hi 👋

Our project has been using `bodyguard` for several years, and thank you for this great library. But I can't help to notice that the project hasn't been updated for 3 years, leading to many deps-related warnings and growing concerns within my team about the viability of using it.

Is the project not maintained due to a lack of time/motivation of the maintainer?

Is the project still maintained, but there was no real need for an update?

Is the project not maintained due to a new and better solution/dependency/practice that my team and I might have missed?

Thanks in advance 🙂

**Comment by goulvenclech** [comment]
@schrockwell Thanks for your answer 🙂 feel free to ping if you need any help with the V3 or maintenance updates!

**Comment by sheharyarn** [comment]
Thank you for the clarification! Maybe it makes sense to communicate some other way that project is still active and maintained?

And thank you for working on the library!
